# -*- coding: utf-8 -*-
"""Vanthudra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NRNRf0uVpUk4NuLVj45UPuCRF2Jpz4Us
"""

!pip install pillow
!pip install lxml
!pip install Cython
!pip install jupyter
!pip install matplotlib
!pip install pandas
!pip install opencv-python
!pip install tensorflow-gpu
!apt-get install -qq protobuf-compiler python-tk
!pip install -q Cython contextlib2 pillow lxml matplotlib PyDrive
!pip install -q pycocotools

!git clone https://github.com/tensorflow/models/

# Commented out IPython magic to ensure Python compatibility.
# %cd models/research/object_detection

!protoc protos/*.proto --python_out=.

import os
os.environ['PYTHONPATH'] += ':/content/models/research/:/content/models/research/slim/'

!python3 models/research/setup.py build

!python3 models/research/setup.py install

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!unzip object-detection.zip

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!python object-detection/generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record --image_dir=images/train

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/object-detection

!python generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record --image_dir=images/train

!python generate_tfrecord.py --csv_input=data/test_labels.csv --output_path=data/test.record --image_dir=images/test

!wget http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_v2_coco_2018_01_28.tar.gz
!tar -xvzf faster_rcnn_inception_v2_coco_2018_01_28.tar.gz
!rm -rf faster_rcnn_inception_v2_coco_2018_01_28.tar.gz

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/models/research/object_detection

!mkdir /content/models/research/object_detection/training

!python3 legacy/train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_coco.config